export const semanticTokens = {
  colors: {
    "bg.canvas": { value: "{colors.navy950}" },
    "bg.section": { value: "{colors.navy900}" },
    "bg.sectionDeep": { value: "{colors.navy950}" },
    "bg.card": { value: "{colors.whiteAlpha120}" },
    "bg.elevated": { value: "{colors.petroleum800}" },
    "bg.headerGlass": { value: "{colors.headerGlass}" },
    fg: { value: "{colors.ice50}" },
    "fg.muted": { value: "{colors.blueGray200}" },
    "fg.subtle": { value: "{colors.blueGray400}" },
    "brand.solid": { value: "{colors.cyan500}" },
    "brand.fg": { value: "{colors.navy950}" },
    "brand.subtle": { value: "{colors.whiteAlpha120}" },
    "brand.emphasized": { value: "{colors.cyan400}" },
    "cta.whatsapp": { value: "{colors.green500}" },
    "cta.whatsappHover": { value: "{colors.green600}" },
    "cta.solid": { value: "{colors.amber400}" },
    "cta.hover": { value: "{colors.amber500}" },
    "cta.contrast": { value: "{colors.navy950}" },
    border: { value: "{colors.whiteAlpha240}" },
    "border.muted": { value: "{colors.whiteAlpha120}" },
    "border.brandSoft": { value: "{colors.whiteAlpha180}" },
  },
} as const
